### PR TITLE
added the python implementation

### PR DESCRIPTION
**Pull request by yuce**
Updated dataset is oming in another PR.

### CODE REVIEW

**Comment by yuce** [comment]
No, this is new. This is a sample python project (which is close to getting started section in the docs).

**Comment by jaffee** [comment]
Ah I see - it does what the docs say to do, but in Python. Can we add some text to the main README and this internal README to make that clear?

**Comment by yuce** [comment]
That makes sense.

**Comment by yuce** [comment]
I'll update the code for the data in the repo and open another PR.

**Pull request closed without merging**
