### PR TITLE
Data update

### PR DESCRIPTION
**Pull request by yuce**
Github search for "star"

### CODE REVIEW

**Comment by yuce** [comment]
@jaffee Doesn't `pilosa import` already sort the data ?

**Comment by yuce** [comment]
@jaffee Isn't 2MB a very low limit? I was thinking there's not enough data in the sample dataset, and maybe using the 30MB one was a better idea :)

**Comment by yuce** [comment]
@jaffee Repository 0 appears more than others, since the repos was sorted by stars.

**Comment by yuce** [comment]
```
$ cat stargazer.csv | cut -f2 -d',' | grep 0 | wc -l
48026
```
Of the 275k repo 0 appears in 48k rows.

**Comment by yuce** [comment]
Sorry, that's wrong, just 19k:
```
$ cat stargazer.csv | grep ',0,' | wc -l
19705
```

**Comment by jaffee** [comment]
I think it would be fine to keep both a small and large data set on hand, but IMO we shouldn't require users to download a 30 meg file just to complete our getting started section.

**Comment by yuce** [comment]
I agree about having small and large versions of the dataset. But even our compressed pilosa binary is 5MB in size.

**Comment by travisturner** [comment]
i haven't reviewed the new data file, but does it significantly improve the sample queries in the getting started? i tend to agree with @jaffee that requiring a large data download just for a getting started doesn't make sense.

also, pilosa will do the sorting internally if it needs to, but it's going to be a lot faster if the data is already sorted.

**Comment by yuce** [comment]
New data files probably don't improve the queries much. Not sure whether publicly discussing the dataset size is a good idea. Closing this PR.

**Pull request closed without merging**
